language: android

node_js:
  - 5.5

notifications:
  email: false

sudo: false

branches:
  only:
  - master

before_install:
  - npm cache clean
  - npm install
  - npm install -g cordova
  - echo y | android update sdk -u --filter android-23,android-24

before_script:
  - rm -rf platforms

script:
  - cordova prepare
  - cordova build android

release:
  - exit 0


language: objective-c
os: osx
osx_image: xcode8
before_install:
  - export LANG=en_US.UTF-8
  - brew update
  - npm install -g npm@2.14.5
  - npm install -g grunt-cli cordova ionic
before_script:
  - rm -rf platforms

script:
  - cordova prepare
  - cordova build android
