
node_js:
  - 5.5

notifications:
  email: false

sudo: false

branches:
  only:
  - master

before_install:
  - wget http://dl.google.com/android/android-sdk_r24.4.1-macosx.zip
  - unzip android-sdk_r24.4.1-macosx.zip
  - export ANDROID_HOME=$PWD/android-sdk-macosx
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null
  - echo yes | android update sdk --filter android-23 --no-ui --force > /dev/null
  - echo yes | android update sdk --filter build-tools-23.0.3 --all --no-ui --force > /dev/null
  - echo yes | android update sdk --filter sysimg-23 --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null
  - npm cache clean
  - npm install -g cordova
  - cordova plugins add cordova-plugin-statusbar
  - echo y | android update sdk -u --filter android-23,android-24

before_script:
  - rm -rf platforms

script:
  - cordova prepare
  - cordova build android
  - cordova build ios

language: objective-c
