language: android

node_js:
  - 5.5

notifications:
  email: false

sudo: false

branches:
  only:
  - master

before_install:
  - npm cache clean
  - npm install -g cordova
  - cordova plugins add cordova-plugin-statusbar
  - echo y | android update sdk -u --filter android-23,android-24

before_script:
  - rm -rf platforms

script:
  - cordova prepare
  - cordova build android
  - cordova build ios
language: objective-c
  os: osx
  osx_image: xcode8
